[project]
name = "criticbox-sd"
version = "0.1.0"
description = ""
authors = [
    {name = "Marco Antonio",email = "marcokjjkk@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grpcio (>=1.60.0)",
    "grpcio-tools (>=1.60.0)",
    "protobuf (>=4.25.0)",
    "tmdbsimple (>=2.9.0)",
    "python-dotenv (>=1.0.0)",
    "fastapi (>=0.141.1,<0.142.0)",
    "uvicorn (>=0.53.0,<0.54.0)"
]

[tool.poetry]
packages = [{include = "criticbox_sd"}]

[tool.poetry.scripts]
api = "criticbox_sd.api.main:start"


[tool.ruff]
line-length = 120
target-version = "py310"
exclude = [
    "generated",
    ".git",
    "__pycache__",
]

[tool.ruff.lint]
select = ["E", "F", "I", "W"]
ignore = ["E402", "E501"]

[tool.ruff.format]
quote-style = "double"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ruff (>=0.16.4,<0.17.0)",
    "httpx (>=0.28.1,<0.29.0)"
]
